// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/north/config_get": {
            "post": {
                "description": "获取配置接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据"
                ],
                "summary": "获取配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录凭证",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求体",
                        "name": "reqestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/constant.Request"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "type": "object"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "gzip": {
                                                            "type": "boolean"
                                                        },
                                                        "version": {
                                                            "type": "string"
                                                        }
                                                    }
                                                }
                                            ]
                                        },
                                        "version": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/constant.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "type": "object"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "nodes": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/constant.SpaceObject"
                                                            }
                                                        },
                                                        "version": {
                                                            "type": "string"
                                                        }
                                                    }
                                                }
                                            ]
                                        },
                                        "error_code": {
                                            "type": "integer"
                                        },
                                        "error_msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/north/heartbeat": {
            "post": {
                "description": "心跳接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "通讯"
                ],
                "summary": "心跳",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录凭证",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/constant.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "type": "object"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "heartbeat_time": {
                                                            "type": "string"
                                                        }
                                                    }
                                                }
                                            ]
                                        },
                                        "error_code": {
                                            "type": "integer"
                                        },
                                        "error_msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/north/history_data_get": {
            "post": {
                "description": "获取历史数据接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据"
                ],
                "summary": "获取历史数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录凭证",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求体",
                        "name": "reqestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/constant.Request"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "type": "object"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "begin_time": {
                                                            "type": "integer"
                                                        },
                                                        "end_time": {
                                                            "type": "integer"
                                                        },
                                                        "point_guids": {
                                                            "type": "array",
                                                            "items": {
                                                                "type": "string"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        },
                                        "version": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/constant.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "type": "object"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "points": {
                                                            "type": "array",
                                                            "items": {
                                                                "allOf": [
                                                                    {
                                                                        "type": "object"
                                                                    },
                                                                    {
                                                                        "type": "object",
                                                                        "properties": {
                                                                            "guid": {
                                                                                "type": "string"
                                                                            },
                                                                            "tag": {
                                                                                "type": "string"
                                                                            },
                                                                            "values": {
                                                                                "type": "array",
                                                                                "items": {
                                                                                    "allOf": [
                                                                                        {
                                                                                            "type": "object"
                                                                                        },
                                                                                        {
                                                                                            "type": "object",
                                                                                            "properties": {
                                                                                                "timestamp": {
                                                                                                    "type": "integer"
                                                                                                },
                                                                                                "value": {
                                                                                                    "type": "string"
                                                                                                }
                                                                                            }
                                                                                        }
                                                                                    ]
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                ]
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        },
                                        "error_code": {
                                            "type": "integer"
                                        },
                                        "error_msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/north/login": {
            "post": {
                "description": "用户登录接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "reqestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/constant.Request"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "type": "object"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "password": {
                                                            "type": "string"
                                                        },
                                                        "username": {
                                                            "type": "string"
                                                        }
                                                    }
                                                }
                                            ]
                                        },
                                        "version": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/constant.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "type": "object"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "login_time": {
                                                            "type": "string"
                                                        },
                                                        "timeout": {
                                                            "type": "integer"
                                                        }
                                                    }
                                                }
                                            ]
                                        },
                                        "error_code": {
                                            "type": "integer"
                                        },
                                        "error_msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        },
                        "headers": {
                            "Token": {
                                "type": "string",
                                "description": "登录凭证"
                            }
                        }
                    }
                }
            }
        },
        "/north/logout": {
            "post": {
                "description": "用户登出接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户登出",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录凭证",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登出成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/constant.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "type": "object"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "logout_time": {
                                                            "type": "string"
                                                        }
                                                    }
                                                }
                                            ]
                                        },
                                        "error_code": {
                                            "type": "integer"
                                        },
                                        "error_msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/north/offline_data_get": {
            "post": {
                "description": "获取离线数据接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据"
                ],
                "summary": "获取离线数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录凭证",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求体",
                        "name": "reqestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/constant.Request"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "type": "object"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "begin_time": {
                                                            "type": "integer"
                                                        },
                                                        "end_time": {
                                                            "type": "integer"
                                                        },
                                                        "strategy_id": {
                                                            "type": "integer"
                                                        }
                                                    }
                                                }
                                            ]
                                        },
                                        "version": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/constant.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "type": "object"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "devices": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/constant.ResponseDevicesPart"
                                                            }
                                                        },
                                                        "strategy_id": {
                                                            "type": "integer"
                                                        }
                                                    }
                                                }
                                            ]
                                        },
                                        "error_code": {
                                            "type": "integer"
                                        },
                                        "error_msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/north/online_data_get": {
            "post": {
                "description": "获取在线数据(请求/响应)接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据"
                ],
                "summary": "获取在线数据(请求/响应)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录凭证",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求体",
                        "name": "reqestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/constant.Request"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "type": "object"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "device_guids": {
                                                            "type": "array",
                                                            "items": {
                                                                "type": "string"
                                                            }
                                                        },
                                                        "point_guids": {
                                                            "type": "array",
                                                            "items": {
                                                                "type": "string"
                                                            }
                                                        },
                                                        "space_guids": {
                                                            "type": "array",
                                                            "items": {
                                                                "type": "string"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        },
                                        "version": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/constant.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "type": "object"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "devices": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/constant.ResponseDevicesPart"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        },
                                        "error_code": {
                                            "type": "integer"
                                        },
                                        "error_msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/north/online_data_strategy_add": {
            "post": {
                "description": "获取在线数据(发布/订阅) - 添加订阅策略接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据"
                ],
                "summary": "获取在线数据(发布/订阅) - 添加订阅策略",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录凭证",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求体",
                        "name": "reqestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/constant.Request"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "type": "object"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "device_guids": {
                                                            "type": "array",
                                                            "items": {
                                                                "type": "string"
                                                            }
                                                        },
                                                        "mode": {
                                                            "type": "integer"
                                                        },
                                                        "name": {
                                                            "type": "string"
                                                        },
                                                        "point_guids": {
                                                            "type": "array",
                                                            "items": {
                                                                "type": "string"
                                                            }
                                                        },
                                                        "space_guids": {
                                                            "type": "array",
                                                            "items": {
                                                                "type": "string"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        },
                                        "version": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/constant.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "type": "object"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "strategy_id": {
                                                            "type": "integer"
                                                        }
                                                    }
                                                }
                                            ]
                                        },
                                        "error_code": {
                                            "type": "integer"
                                        },
                                        "error_msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/north/online_data_strategy_del": {
            "post": {
                "description": "获取在线数据(发布/订阅) - 删除订阅策略接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据"
                ],
                "summary": "获取在线数据(发布/订阅) - 删除订阅策略",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录凭证",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求体",
                        "name": "reqestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/constant.Request"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "type": "object"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "strategy_id": {
                                                            "type": "integer"
                                                        }
                                                    }
                                                }
                                            ]
                                        },
                                        "version": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/constant.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        },
                                        "error_code": {
                                            "type": "integer"
                                        },
                                        "error_msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/north/online_data_strategy_push": {
            "post": {
                "description": "获取在线数据(发布/订阅) - 推送数据(客户端侧)接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据"
                ],
                "summary": "获取在线数据(发布/订阅) - 推送数据(客户端侧)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录凭证",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求体",
                        "name": "reqestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/constant.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "type": "object"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "devices": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/constant.ResponseDevicesPart"
                                                            }
                                                        },
                                                        "strategy_id": {
                                                            "type": "integer"
                                                        }
                                                    }
                                                }
                                            ]
                                        },
                                        "version": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/constant.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        },
                                        "error_code": {
                                            "type": "integer"
                                        },
                                        "error_msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/north/online_data_strategy_query": {
            "post": {
                "description": "获取在线数据(发布/订阅) - 查询订阅策略接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据"
                ],
                "summary": "获取在线数据(发布/订阅) - 查询订阅策略",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录凭证",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求体",
                        "name": "reqestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/constant.Request"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        },
                                        "version": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/constant.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "type": "object"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "strategies": {
                                                            "type": "array",
                                                            "items": {
                                                                "allOf": [
                                                                    {
                                                                        "type": "object"
                                                                    },
                                                                    {
                                                                        "type": "object",
                                                                        "properties": {
                                                                            "device_guids": {
                                                                                "type": "array",
                                                                                "items": {
                                                                                    "type": "string"
                                                                                }
                                                                            },
                                                                            "mode": {
                                                                                "type": "integer"
                                                                            },
                                                                            "point_guids": {
                                                                                "type": "array",
                                                                                "items": {
                                                                                    "type": "string"
                                                                                }
                                                                            },
                                                                            "space_guids": {
                                                                                "type": "array",
                                                                                "items": {
                                                                                    "type": "string"
                                                                                }
                                                                            },
                                                                            "strategy_id": {
                                                                                "type": "integer"
                                                                            }
                                                                        }
                                                                    }
                                                                ]
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        },
                                        "error_code": {
                                            "type": "integer"
                                        },
                                        "error_msg": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "constant.DeviceObject": {
            "type": "object",
            "properties": {
                "device_type": {
                    "type": "integer"
                },
                "guid": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "node_type": {
                    "type": "integer"
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/constant.PointObject"
                    }
                },
                "path": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                }
            }
        },
        "constant.PointObject": {
            "type": "object",
            "properties": {
                "abs_value": {
                    "type": "number"
                },
                "alarm_level": {
                    "type": "integer"
                },
                "alarm_type": {
                    "type": "integer"
                },
                "ao_bound": {
                    "type": "string"
                },
                "guid": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "node_type": {
                    "type": "integer"
                },
                "path": {
                    "type": "string"
                },
                "percentage": {
                    "type": "number"
                },
                "period": {
                    "type": "integer"
                },
                "status_map": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "constant.Request": {
            "type": "object",
            "required": [
                "data",
                "version"
            ],
            "properties": {
                "data": {
                    "type": "object"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "constant.Response": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object"
                },
                "error_code": {
                    "type": "integer"
                },
                "error_msg": {
                    "type": "string"
                }
            }
        },
        "constant.ResponseDevicesPart": {
            "type": "object",
            "properties": {
                "guid": {
                    "type": "string"
                },
                "points": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/constant.ResponsePointsPart"
                    }
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "constant.ResponsePointsPart": {
            "type": "object",
            "properties": {
                "guid": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "integer"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "constant.SpaceObject": {
            "type": "object",
            "properties": {
                "guid": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "node_type": {
                    "type": "integer"
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/constant.DeviceObject"
                    }
                },
                "path": {
                    "type": "string"
                },
                "space_type": {
                    "type": "integer"
                },
                "tag": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "127.0.0.1:8080",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "北向API接口",
	Description: "北向API接口",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
